# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
os:
  - linux
  - osx
dist: trusty

# Unbreak clang address sanitizer, needs SYS_PTRACE
# https://github.com/google/sanitizers/issues/764#issuecomment-276663297
# https://github.com/travis-ci/travis-ci/issues/9033
sudo: required

git:
  depth: 1

env:
  global:
    - CFLAGS='-g -pipe'
  matrix:
    - MODE=address
    - MODE=cmake
    - MODE=cmake-oos
    - MODE=distcheck
    - MODE=lib-coverage

matrix:
  exclude:
    - os: osx
      env: MODE=lib-coverage

addons:
  homebrew:
    update: true
    brewfile: true
  apt:
    packages:
      - cmake
      - docbook2x
      - dos2unix
      - lzip
      - rpm

script:
  - ./.travis.sh
