# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
os:
  - linux
  - osx
dist: trusty

git:
  depth: 50

env:
  global:
    - CFLAGS='-g -pipe'
  matrix:
    - MODE=cmake-oos
    - MODE=cppcheck
    - MODE=distcheck
    - MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=address

matrix:
  include:
    - os: linux
      env: MODE=cmake-oos CMAKE_ARGS=-DXML_ATTR_INFO=ON
    - os: linux
      env: MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=address CONFIGURE_ARGS=--enable-xml-attr-info
    - os: linux
      env: MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=memory
    - os: linux
      env: MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=undefined
    - os: linux
      env: MODE=qa-sh QA_COMPILER=gcc CC=gcc CXX=g++ LD=ld QA_PROCESSOR=gcov

addons:
  homebrew:
    update: true
    brewfile: true
  apt:
    sources:
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
    packages:
      - clang-9
      - cmake
      - cppcheck
      - docbook2x
      - dos2unix
      - lzip
      - rpm

script:
  - ./.travis.sh
