#                          __  __            _
#                       ___\ \/ /_ __   __ _| |_
#                      / _ \\  /| '_ \ / _` | __|
#                     |  __//  \| |_) | (_| | |_
#                      \___/_/\_\ .__/ \__,_|\__|
#                               |_| XML parser
#
# Copyright (c) 2021-2022 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license:
#
# Permission is  hereby granted,  free of charge,  to any  person obtaining
# a  copy  of  this  software   and  associated  documentation  files  (the
# "Software"),  to  deal in  the  Software  without restriction,  including
# without  limitation the  rights  to use,  copy,  modify, merge,  publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit
# persons  to whom  the Software  is  furnished to  do so,  subject to  the
# following conditions:
#
# The above copyright  notice and this permission notice  shall be included
# in all copies or substantial portions of the Software.
#
# THE  SOFTWARE  IS  PROVIDED  "AS  IS",  WITHOUT  WARRANTY  OF  ANY  KIND,
# EXPRESS  OR IMPLIED,  INCLUDING  BUT  NOT LIMITED  TO  THE WARRANTIES  OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR  COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR  OTHER LIABILITY, WHETHER  IN AN  ACTION OF CONTRACT,  TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
# USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Collect test coverage

on:
  pull_request:
  push:
  schedule:
    - cron: '0 2 * * 5'  # Every Friday at 2am

jobs:
  checks:
    name: Collect test coverage
    runs-on: ubuntu-18.04
    env:
      CFLAGS: -g3 -pipe
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Add Clang/LLVM repositories
      run: |-
        set -x
        source /etc/os-release
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/${UBUNTU_CODENAME}/ llvm-toolchain-${UBUNTU_CODENAME}-14 main"
    - name: Install build dependencies
      # NOTE: Please note the version-specific ${PATH} extension for Clang in .travis.sh
      run: |-
        sudo dpkg --add-architecture i386  # for wine32
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends -V \
            clang-14 \
            clang-format-14 \
            llvm-14 \
            cmake \
            docbook2x \
            dos2unix \
            gcc-multilib \
            g++-multilib \
            lcov \
            libbsd-dev \
            lzip \
            mingw-w64 \
            moreutils \
            wine-stable \
            wine32
    - name: Unshallow Git clone
      run: |
        git fetch --force --tags --unshallow origin  # for "git describe" in coverage.sh
    - name: Collect test coverage
      env:
        MODE: coverage-sh
        TRAVIS_OS_NAME: linux
      run: |
        exec ./.travis.sh

    - name: Store coverage .info and HTML report
      uses: actions/upload-artifact@v3.0.0
      with:
        name: coverage
        path: expat/coverage__*/
        if-no-files-found: error
